<a href="https://colab.research.google.com/github/IU2441230156collegework/PSC_College_work/blob/main/IU2441230156_Module3_Module13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Write a Python program to check whether a specified value is contained in a group of values using lambda function.
    Test Data: 3 -> [1, 5, 8, 3] : True , -1 -> [1, 5, 8, 3] : False

In [30]:
test_data = [1,5,8,3]
target =3;
result = lambda x , y : x in y
print(result(target,test_data))
print(result(-1,test_data))

True
False


#2. Write a Python program to find whether a given string ends with a given character using Lambda.

In [31]:
flag = lambda x, y: x == y[len(y)-1]
print(flag('c' , "python"))
print(flag('n' , "python"))

False
True


#3. Prime or not prime. Input: L= [3,4,6,9,11] Output: L= [P, NP, NP, NP, P] using map function.

In [1]:
def check_prime(n):
  if(n<=1):
    return 'NP'
  for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return 'NP'
  return 'P'

check_prime_not_prime = list(map(check_prime,[3,4,6,9,11]))
print(check_prime_not_prime)

['P', 'NP', 'NP', 'NP', 'P']


#4 Write a python program to find out even numbers from a list using filter ().

In [2]:
even_list = list(filter(lambda x : x%2 == 0 ,[0,1,2,3,4,5,6,7,8,9]))
print(even_list)

[0, 2, 4, 6, 8]


#Extract all odd numbers from the array using “where” clause.

In [5]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9])
odd_number = arr[np.where(arr %2 != 0)]
print("odd numbers",odd_number)

odd numbers [1 3 5 7 9]


#2. Replace all odd numbers in array with -1

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


#3. Convert a 1D array to a 2D array with 2 rows and 5 columns.

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = arr.reshape(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#4. Get the common items between array1 and array2.
     Input: array1 = [1,2,3,2,3,4,3,4,5,6],array2 = [7,2,10,2,7,4,9,4,9,8]
     Desired Output: array([2, 4])

In [11]:
import numpy as np
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array( [7,2,10,2,7,4,9,4,9,8])
arrresult = np.intersect1d(arr1,arr2)
print(arrresult)

[2 4]


#5. Perform Matrix multiplication on 2 matrices.

In [13]:
import numpy as np
matrix_A = np.array([[1,2],[3,4]])
matrix_B = np.array([[5,6],[7,8]])
result_matrix = matrix_A @ matrix_B
print(result_matrix)

[[19 22]
 [43 50]]
