<a href="https://colab.research.google.com/github/IU2441230156collegework/PSC_College_work/blob/main/IU2441230156_module6_module1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4. Write a Python program to print out a set containing all the colours from color_list_1 which are not present in color_list_2.
    Test Data: color_list_1 = set (["White", "Black", "Red"]),color_list_2 = set (["Red", "Green"]) Expected Output: {'Black', 'White'}

In [ ]:
color_list_1 = {"White", "Black", "Red"}
color_list_2 = {"Red", "Green"}
result = color_list_1 - color_list_2
print(result)

{'Black', 'White'}


7. Write a menu driven program to implement the following methods on set. (1) Create (2) Update particular element of set (3) Append to          the set (4) Delete whole set (5) Delete particular element (6) Sort the set (7) Find length

In [ ]:
s = set()
print("\n----- MENU -----")
print("1. Create Set")
print("2. Update Particular Element")
print("3. Append to Set")
print("4. Delete Whole Set")
print("5. Delete Particular Element")
print("6. Sort the Set")
print("7. Find Length")
print("8. Exit")
while True:

    choice = int(input("Enter your choice: "))
    if choice == 1:
        n = int(input("Enter number of elements: "))
        s = set()
        for i in range(n):
            x = input("Enter element: ")
            s.add(x)
        print("Set is:", s)

    elif choice == 2:
        old = input("Enter element to update: ")
        if old in s:
            new = input("Enter new element: ")
            s.remove(old)
            s.add(new)
            print("Updated Set:", s)
        else:
            print("Element not found.")

    elif choice == 3:
        x = input("Enter element to append: ")
        s.add(x)
        print("Set after appending:", s)

    elif choice == 4:
        s.clear()
        print("Whole set deleted.")

    elif choice == 5:
        x = input("Enter element to delete: ")
        if x in s:
            s.remove(x)
            print("Set after deletion:", s)
        else:
            print("Element not found.")

    elif choice == 6:
        temp = list(s)
        temp.sort()
        print("Sorted Set:", temp)

    elif choice == 7:
        print("Length of set is:", len(s))

    elif choice == 8:
        print("Program Ended.")
        break

    else:
        print("Invalid Choice.")


----- MENU -----
1. Create Set
2. Update Particular Element
3. Append to Set
4. Delete Whole Set
5. Delete Particular Element
6. Sort the Set
7. Find Length
8. Exit
Enter your choice: 1
Enter number of elements: 3
Enter element: 2
Enter element: 1
Enter element: 3
Set is: {'1', '3', '2'}
Enter your choice: 2
Enter element to update: 2
Enter new element: 5
Updated Set: {'1', '3', '5'}
Enter your choice: 3
Enter element to append: 4
Set after appending: {'1', '3', '4', '5'}
Enter your choice: 5
Enter element to delete: 4
Set after deletion: {'1', '3', '5'}
Enter your choice: 6
Sorted Set: ['1', '3', '5']
Enter your choice: 7
Length of set is: 3
Enter your choice: 4
Whole set deleted.
Enter your choice: 8
Program Ended.


1. Demonstrate functions and all categories of functions in C/C++/java/python.

In [ ]:
#1 Demonstrate functions and all categories of functions in C/C++/java/python.
"""
Demonstration of Functions and Categories of Functions
Categories:
1. No Arguments, No Return Value
2. Arguments, No Return Value
3. No Arguments, Return Value
4. Arguments, Return Value
"""
# -------------------------------------------------
# 1. No Arguments, No Return Value
# -------------------------------------------------
def greet():
  print("Hello! Welcome to Python Functions.")
# -------------------------------------------------
# 2. Arguments, No Return Value
# -------------------------------------------------
def add(a, b):
  print("Sum =", a + b)
# -------------------------------------------------
# 3. No Arguments, Return Value
# -------------------------------------------------
def message():
  return "Python Programming"
# -------------------------------------------------
# 4. Arguments, Return Value
# -------------------------------------------------
def multiply(a, b):
  return a * b
# Function Calls
print("1. No Arguments, No Return Value")
greet()
print("\n2. Arguments, No Return Value")
add(10, 20)
print("\n3. No Arguments, Return Value")
msg = message()
print("Returned Value:", msg)
print("\n4. Arguments, Return Value")
result = multiply(5, 6)
print("Multiplication =", result)
"""
====================================================
C PROGRAM (Commented as Multi-line Comment)
====================================================
#include <stdio.h>
// No Arguments, No Return Value
void greet()
{
printf("Hello! Welcome to C Functions\n");
}
// Arguments, No Return Value
void add(int a, int b)
{
printf("Sum = %d\n", a + b);
}
/ No Arguments, Return Value
int number()
{
return 100;
}
// Arguments, Return Value
int multiply(int a, int b)
{
return a * b;
}
int main()
{
greet();
add(10,20);
int n = number();
printf("Returned Value = %d\n", n);
printf("Multiplication = %d", multiply(5,6));
return 0;
}
====================================================
C++ PROGRAM
====================================================
#include <iostream>
using namespace std;
// No Arguments, No Return Value
void greet()
{
cout << "Hello! Welcome to C++ Functions" << endl;
}
// Arguments, No Return Value
void add(int a, int b)
{
cout << "Sum = " << a+b << endl;
}
// No Arguments, Return Value
int number()
{
return 100;
}
// Arguments, Return Value
int multiply(int a, int b)
{
return a*b;
}
int main()
{
greet();
add(10,20);
cout << "Returned Value = " << number() << endl;
cout << "Multiplication = " << multiply(5,6);
return 0;
}
====================================================
JAVA PROGRAM
====================================================
class FunctionsDemo
{
// No Arguments, No Return Value
static void greet()
{
System out println("Hello! Welcome to Java Functions");
}
// Arguments, No Return Value
static void add(int a, int b)
{
System.out.println("Sum = " + (a+b));
}
// No Arguments, Return Value
static int number()
{
return 100;
}
// Arguments, Return Value
static int multiply(int a, int b)
{
return a*b;
}
public static void main(String args[])
{
greet();
add(10,20);
System.out.println("Returned Value = " + number());
System.out.println("Multiplication = " + multiply(5,6));
}
}
"""

#2 Demonstrate arrays (Insertion, Deletion, arithmetic operations). from array

In [ ]:
from array import *
# Create an array
arr = array('i', [10,20,30,40,50])
print("Original Array:", arr)
# Insertion
arr.insert(2,25)
print("After Insertion:", arr)
# Deletion
arr.remove(40)
print("After Deletion:", arr)
# Arithmetic Operations
print
("\nArithmetic Operations:")
print("Addition:")
for i in arr:
  print(i,"+ 5 =", i +5)
  print("\nSubtraction:")
for i in arr:
  print(i,"- 5 =", i -5)
  print("\nMultiplication:")
for i in arr:
  print(i,"* 2 =", i *2)
  print("\nDivision:")
for i in arr:
  print(i,"/ 2 =", i /2)

Original Array: array('i', [10, 20, 30, 40, 50])
After Insertion: array('i', [10, 20, 25, 30, 40, 50])
After Deletion: array('i', [10, 20, 25, 30, 50])
Addition:
10 + 5 = 15

Subtraction:
20 + 5 = 25

Subtraction:
25 + 5 = 30

Subtraction:
30 + 5 = 35

Subtraction:
50 + 5 = 55

Subtraction:
10 - 5 = 5

Multiplication:
20 - 5 = 15

Multiplication:
25 - 5 = 20

Multiplication:
30 - 5 = 25

Multiplication:
50 - 5 = 45

Multiplication:
10 * 2 = 20

Division:
20 * 2 = 40

Division:
25 * 2 = 50

Division:
30 * 2 = 60

Division:
50 * 2 = 100

Division:
10 / 2 = 5.0
20 / 2 = 10.0
25 / 2 = 12.5
30 / 2 = 15.0
50 / 2 = 25.0


#3 Matrix multiplication and vector matrix

In [ ]:
import numpy as np
# -------- Vector Operations --------
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("Vector 1:", v1)
print("Vector 2:", v2)
# Vector Addition
print("Vector Addition:", v1 + v2)
# Vector Multiplication (Element-wise)
print("Vector Multiplication:", v1 * v2)
# -------- Matrix Operations --------
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print("\nMatrix 1:")
print(m1)
print("\nMatrix 2:")
print(m2)
# Matrix Addition
print("\nMatrix Addition:")
print(m1 + m2)
# Matrix Multiplication
print("\nMatrix Multiplication:")
print(np.dot(m1, m2))

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Vector Addition: [5 7 9]
Vector Multiplication: [ 4 10 18]

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Multiplication:
[[19 22]
 [43 50]]


# Practical based on Strings (Length finding, change specific character,
# palindrome,concatenation)
# String Operations

In [ ]:

# Input Strings
str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
# 1. Find Length
print("Length of first string:" ,len(str1))
# 2. Change Specific Character
index = int(input("Enter index to change: "))
new_char = input("Enter new character: ")
if 0 <= index < len(str1):
  str1 = str1[:index] + new_char + str1[index + 1:]
  print("Updated String:", str1)
else:
  print("Invalid index!")
# 3. Palindrome Check
if str1 == str1[::-1]:
  print("The string is a Palindrome.")
else:
  print("The string is Not a Palindrome.")
# 4. Concatenation
result = str1 + str2
print("Concatenated String:", result)

Enter first string: Hello
Enter second string: world
Length of first string: 5
Enter index to change: 1
Enter new character: a
Updated String: Hallo
The string is Not a Palindrome.
Concatenated String: Halloworld


In [ ]:
# Menu Driven Program for Python Operators

print("\n----- MENU -----")
print("1. Arithmetic Operators")
print("2. Comparison Operators")
print("3. Logical Operators")
print("4. Assignment Operators")
print("5. Exit")

while True:
    choice = int(input("Enter your choice: "))

    if choice == 1:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))

        print("Addition:", a + b)
        print("Subtraction:", a - b)
        print("Multiplication:", a * b)
        print("Division:", a / b)
        print("Modulus:", a % b)
        print("Exponent:", a ** b)
        print("Floor Division:", a // b)

    elif choice == 2:
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))

        print("a == b :", a == b)
        print("a != b :", a != b)
        print("a > b :", a > b)
        print("a < b :", a < b)
        print("a >= b :", a >= b)
        print("a <= b :", a <= b)

    elif choice == 3:
        x = bool(int(input("Enter first value (1=True, 0=False): ")))
        y = bool(int(input("Enter second value (1=True, 0=False): ")))

        print("AND:", x and y)
        print("OR :", x or y)
        print("NOT x:", not x)

    elif choice == 4:
        a = int(input("Enter a number: "))

        print("Original Value:", a)
        a += 5
        print("After += 5:", a)
        a -= 2
        print("After -= 2:", a)
        a *= 3
        print("After *= 3:", a)
        a /= 2
        print("After /= 2:", a)

    elif choice == 5:
        print("Program Ended.")
        break

    else:
        print("Invalid Choice")


----- MENU -----
1. Arithmetic Operators
2. Comparison Operators
3. Logical Operators
4. Assignment Operators
5. Exit
Enter your choice: 1
Enter first number: 4
Enter second number: 2
Addition: 6
Subtraction: 2
Multiplication: 8
Division: 2.0
Modulus: 0
Exponent: 16
Floor Division: 2
Enter your choice: 2
Enter first number: 12
Enter second number: 13
a == b : False
a != b : True
a > b : False
a < b : True
a >= b : False
a <= b : True
Enter your choice: 3
Enter first value (1=True, 0=False): 1
Enter second value (1=True, 0=False): 2
AND: True
OR : True
NOT x: False
Enter your choice: 4
Enter a number: 4
Original Value: 4
After += 5: 9
After -= 2: 7
After *= 3: 21
After /= 2: 10.5
Enter your choice: 5
Program Ended.
